fizzy-inc:

  # Site Information
  company:      Fizzy Inc.
  title:        "We Are Digital Storytellers"
  subtitle:     "We build websites that engage your users and add value to your brand."
  cover_image:  mountaineer.jpg
  logo:         logo.png

  # Social Information
  facebook:     fizzymedia
  twitter:      fizzymedia
  gplus:
  email:        hello@fizzyinc.com

  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  false

  # Sharing settings
  sharing:
    twitter:    false
    facebook:   false
    gplus:      false
    hn:         false

 # Analytics
  analytics:
    google:
      # eg. 'UA-123-12'
      id:       false

  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font: 'Droid+Sans:400,700'


# Base directory settings
# Site.url is set separately in development and production config files
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     ['codekit-config.json', 'config.rb', 'Gemfile', 'Gemfile.lock', 'Rakefile', 'doc', 'jekyll-incorportated-originals']
timezone:    nil

# The following line let us use compass --watch or codekit to process the scss
keep_files:  ['css']

# Show future posts
future:      false
show_drafts: nil
limit_posts: 0
pygments:    true

relative_permalinks: true

permalink:     "/blog/:title/"
paginate_path: 'blog/page:num'
paginate: 10

markdown:      maruku
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "<!-- more -->"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     ''
lsi:         false

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    img/latex
  png_url:    /img/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true