inc:
  # Blog Information
  title:        "Fizzy Journal"
  subtitle:     "We Are Digital Storytellers."
  cover_image:  blog-cover.jpg
  logo:         logo.png

  # Company information
  company:      Fizzy Inc.
  url:          http://fizzyinc.com/
  facebook:     fizzymedia
  twitter:      fizzymedia
  gplus:
  about_link:   http://fizzyinc.com/about

  # Product Information
  product_link: http://fizzyinc.com/services
  tagline:      "Let's build something awesome together"

  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  false

  # Sharing settings
  sharing:
    twitter:    false
    facebook:   false
    gplus:      false
    hn:         false


 # Analytics
  analytics:
    google:
      # eg. 'UA-123-12'
      id:       false


  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font: 'Droid+Sans:400,700'

  # Setup your fonts, colors etc at _assets/stylesheets/main.scss

url:         http://fizzyinc.com
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     ['codekit-config.json', 'config.rb', 'Gemfile', 'Gemfile.lock', 'Rakefile']
# The following line let us use compass --watch or codekit to process the scss
keep_files:  ['css']
timezone:    nil

# Show future posts
future:      false
show_drafts: nil
limit_posts: 0
pygments:    true

relative_permalinks: true

permalink:     pretty
paginate_path: 'page:num'
paginate: 10

markdown:      maruku
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "<!-- more -->"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /blog
lsi:         false

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true